import statistics

print("WSQ-07")
print("Ingresa el primer número")
a = float(input())
print("Ingresa el segundo número")
b = float(input())
print("Ingresa el tercer número")
c = float(input())
print("Ingresa el cuarto número")
d = float(input())
print("Ingresa el quinto número")
e = float(input())
print("Ingresa el sexto número")
f = float(input())
print("Ingresa el septimo número")
g = float(input())
print("Ingresa el octavo número")
h = float(input())
print("Ingresa el noveno número")
i = float(input())
print("Ingresa el décimo número")
j = float(input())
l = [a,b,c,d,e,f,g,h,i,j]
print("La suma total de tus números es de ", sum(l))
print("El promedio de tus números es de ", statistics.mean(l))
print("La desviación estándar de tus números es de ", statistics.stdev(l))
